name: Terraform Infra Plan - AP Southeast 1
on:
  pull_request:
    paths:
      - 'infra/int/ap-southeast-1/**'
    types:
      - closed
    branches:
      - main
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
jobs:
  call-terraform-plan-workflow:
    uses: ./.github/workflows/terraform_plan_workflow.yml
    with:
      region: ap-southeast-1
